import React,{useMemo,useState} from 'react';
import {FlatList,Image,Pressable,ScrollView,StyleSheet,Text,TextInput,useWindowDimensions,View} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {PRODUCTS} from './catalog';
import FASHION_IMAGES from './assets/fashion-images';
import {money} from './journey';
import {filterProducts,SIZES} from './fashion';
export function CatalogImage({item,style}) {
 const [failed,setFailed]=useState(false);
 const source=item.imageKey?FASHION_IMAGES[item.imageKey]:item.image?{uri:item.image}:null;
 if(failed||!source)return <View style={[style,{backgroundColor:'#f1eaf1',justifyContent:'center',alignItems:'center'}]}><Ionicons name="shirt-outline" size={38} color="#ac7390"/><Text style={{fontSize:10,color:'#82677a'}}>Style preview unavailable</Text></View>;
 return <Image source={source} style={[style,{backgroundColor:'white'}]} resizeMode="contain" accessibilityLabel={item.name} onError={()=>setFailed(true)}/>;
}
function Pills({values,value,onChange}) {return <ScrollView horizontal showsHorizontalScrollIndicator={false} keyboardShouldPersistTaps="handled" contentContainerStyle={f.pills}>{values.map(v=><Pressable key={v} accessibilityRole="button" accessibilityState={{selected:value===v}} style={[f.pill,value===v&&f.active]} onPress={()=>onChange(v)}><Text style={[f.pillLabel,value===v&&f.activeLabel]}>{v}</Text></Pressable>)}</ScrollView>;}
export default function FashionStore({onOpen,cartCount=0,favorites=[],onFavorite=()=>{},onCart=()=>{},searchFirst=false}) {
 const [query,setQuery]=useState(''),[category,setCategory]=useState('All'),[color,setColor]=useState('All'),[size,setSize]=useState('All'),[occasion,setOccasion]=useState('All'),[sort,setSort]=useState('Featured'),[department,setDepartment]=useState('Fashion'),[favoritesOnly,setFavoritesOnly]=useState(false),[filters,setFilters]=useState(false),[az,setAz]=useState(false);
 const {width}=useWindowDimensions();const columns=width>=700?3:2;const cardWidth=(width-40-(columns-1)*12)/columns;
 const pool=PRODUCTS.filter(p=>department==='Fashion'?p.isFashion:!p.isFashion);
 const categories=useMemo(()=>['All',...new Set(pool.map(p=>p.category).sort())],[department]);
 const colors=useMemo(()=>['All',...new Set(pool.map(p=>p.color).sort())],[department]);
 const occasions=['All','Everyday','Work','Party','Vacation','Workout','At home','Traditional'];
 const results=useMemo(()=>filterProducts(PRODUCTS,{query,department,category,color,size,occasion,sort,favoritesOnly,favorites}),[query,department,category,color,size,occasion,sort,favoritesOnly,favorites]);
 const clear=()=>{setQuery('');setCategory('All');setColor('All');setSize('All');setOccasion('All');setFavoritesOnly(false);setSort('Featured');};
 const changeDepartment=value=>{setDepartment(value);clear();};
 const header=<View style={f.header}>
  <View style={f.row}><View><Text style={f.kicker}>CARTPLAY · THE STYLE EDIT · 0.3</Text><Text style={f.logo}>{searchFirst?'Find your next look':'Your dream wardrobe'}</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Open cart" onPress={onCart} style={f.cart}><Ionicons name="bag-handle-outline" size={24} color="#312132"/><Text style={f.cartCount}>{cartCount}</Text></Pressable></View>
  <Text style={f.disclosure}>SHOPPING GAME · USD GAME PRICES · $0 CHARGED</Text>
  {!searchFirst&&<View style={f.hero}><View style={{flex:1}}><Text style={f.heroKicker}>TRY A WHOLE NEW YOU</Text><Text style={f.heroTitle}>A closet{`\n`}without limits.</Text><Text style={f.heroNote}>{PRODUCTS.filter(p=>p.isFashion).length.toLocaleString()} styles to explore. No real spending.</Text></View><Text style={f.heroArt}>✦</Text></View>}
  <View style={f.search}><Ionicons name="search" size={20} color="#83677d"/><TextInput testID="fashion-search" placeholder="Search dresses, kurtas, jeans, heels…" placeholderTextColor="#9a8796" value={query} onChangeText={setQuery} style={f.input}/>{query!==''&&<Pressable accessibilityLabel="Clear search" onPress={()=>setQuery('')}><Ionicons name="close-circle" size={20} color="#97738c"/></Pressable>}</View>
  <View style={f.row}><Pills values={['Fashion','Extras']} value={department} onChange={changeDepartment}/><Pressable accessibilityRole="button" accessibilityState={{selected:favoritesOnly}} onPress={()=>setFavoritesOnly(!favoritesOnly)} style={f.control}><Ionicons name={favoritesOnly?'heart':'heart-outline'} size={19} color="#ae486f"/><Text style={f.controlText}>Saved {favorites.length}</Text></Pressable></View>
  <View style={f.row}><Text style={f.h2}>Shop by category</Text><Pressable accessibilityRole="button" onPress={()=>setAz(!az)}><Text style={f.link}>{az?'Close categories':'Browse A–Z'}</Text></Pressable></View>
  {az?<View style={f.categoryGrid}>{categories.map(c=><Pressable accessibilityRole="button" key={c} style={[f.categoryTile,category===c&&f.active]} onPress={()=>{setCategory(c);setAz(false);}}><Text style={[f.pillLabel,category===c&&f.activeLabel]}>{c}</Text><Text style={[f.categoryCount,category===c&&f.activeLabel]}>{c==='All'?pool.length:pool.filter(p=>p.category===c).length}</Text></Pressable>)}</View>:<Pills values={categories} value={category} onChange={setCategory}/>}
  <View style={f.row}><Text style={f.resultCount}>{results.length} finds{category!=='All'?` · ${category}`:''}</Text><Pressable accessibilityRole="button" onPress={()=>setFilters(!filters)} style={f.control}><Ionicons name="options-outline" size={19} color="#63405a"/><Text style={f.controlText}>{filters?'Close filters':'Filter & sort'}</Text></Pressable></View>
  {filters&&<View style={f.filterPanel}><Text style={f.h2}>Sort by</Text><Pills values={['Featured','Price ↑','Price ↓','A–Z']} value={sort} onChange={setSort}/><Text style={f.h2}>Color shown</Text><Pills values={colors} value={color} onChange={setColor}/><Text style={f.h2}>Game size</Text><Pills values={['All',...SIZES,'US 5','US 6','US 7','US 8','US 9','US 10','US 11','One size']} value={size} onChange={setSize}/><Text style={f.h2}>Occasion</Text><Pills values={occasions} value={occasion} onChange={setOccasion}/><Pressable accessibilityRole="button" onPress={clear}><Text style={f.link}>Clear all filters</Text></Pressable></View>}
  <Text style={f.note}>{department==='Fashion'?'Choose a look, select a size, and send it on a virtual delivery adventure. Nothing is purchased or shipped.':'Six additional virtual collectibles.'}</Text>
 </View>;
 return <FlatList key={columns} data={results} numColumns={columns} keyExtractor={p=>p.id} ListHeaderComponent={header} columnWrapperStyle={{gap:12}} contentContainerStyle={{paddingHorizontal:20,paddingBottom:115}} keyboardShouldPersistTaps="handled" initialNumToRender={8} maxToRenderPerBatch={8} windowSize={7} removeClippedSubviews={false} ListEmptyComponent={<View style={f.empty}><Text style={f.h2}>{favoritesOnly?'No saved styles match yet':'No styles match these filters'}</Text><Text style={f.note}>Try a wider category or clear your filters.</Text><Pressable onPress={clear}><Text style={f.link}>Reset filters</Text></Pressable></View>} renderItem={({item})=><View style={[f.card,{width:cardWidth}]}>
   <Pressable accessibilityRole="button" accessibilityLabel={`View ${item.name}`} onPress={()=>onOpen(item)}><CatalogImage item={item} style={{width:'100%',height:Math.min(235,cardWidth*1.2)}}/><View style={f.cardBody}><Text style={f.cardCategory}>{item.category.toUpperCase()}</Text><Text style={f.productName} numberOfLines={2}>{item.name}</Text><Text style={f.color}>{item.color}{item.sizes?.length?` · ${item.sizes.length} game sizes`:''}</Text><View style={f.row}><Text style={f.price}>{money(item.price)}</Text><View style={f.choose}><Ionicons name="add" size={19} color="#fff"/></View></View></View></Pressable>
   <Pressable accessibilityRole="button" accessibilityLabel={`${favorites.includes(item.id)?'Unsave':'Save'} ${item.name}`} onPress={()=>onFavorite(item.id)} style={f.heart}><Ionicons name={favorites.includes(item.id)?'heart':'heart-outline'} size={20} color="#b44371"/></Pressable>
 </View>}/>;
}
const f=StyleSheet.create({header:{paddingTop:20,paddingBottom:16,gap:12},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},kicker:{fontSize:9,letterSpacing:1.3,fontWeight:'800',color:'#aa6d87'},logo:{fontSize:24,fontWeight:'900',letterSpacing:-0.7,color:'#332432'},cart:{width:44,height:44,borderRadius:22,backgroundColor:'#f8e8ee',alignItems:'center',justifyContent:'center'},cartCount:{position:'absolute',right:0,top:-2,fontSize:10,color:'white',backgroundColor:'#a94873',borderRadius:8,paddingHorizontal:4},disclosure:{fontSize:8,fontWeight:'800',letterSpacing:0.6,color:'#956482'},hero:{borderRadius:26,backgroundColor:'#452e43',padding:22,flexDirection:'row',alignItems:'center',minHeight:175},heroKicker:{fontSize:9,letterSpacing:1.4,color:'#e7afc8',fontWeight:'900'},heroTitle:{fontSize:32,lineHeight:36,fontWeight:'900',color:'#fff3f7',marginTop:10},heroNote:{fontSize:11,color:'#e5bdd0',marginTop:12},heroArt:{fontSize:85,color:'#e1a7c5'},search:{flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:13,height:47,backgroundColor:'white',borderWidth:1,borderColor:'#eaddE6',borderRadius:15},input:{flex:1,fontSize:13,color:'#382d38',outlineStyle:'none'},pills:{gap:7,paddingVertical:8},pill:{paddingVertical:9,paddingHorizontal:13,borderRadius:20,backgroundColor:'white',borderWidth:1,borderColor:'#e9dce5'},active:{backgroundColor:'#683e59',borderColor:'#683e59'},pillLabel:{fontSize:12,color:'#75576b',fontWeight:'700'},activeLabel:{color:'white'},h2:{fontSize:15,fontWeight:'800',color:'#3f2d3b'},link:{fontSize:12,fontWeight:'800',color:'#a94e7b',paddingVertical:6},control:{flexDirection:'row',gap:5,alignItems:'center',paddingVertical:6},controlText:{fontSize:12,color:'#714e65',fontWeight:'700'},categoryGrid:{flexDirection:'row',flexWrap:'wrap',gap:8},categoryTile:{flexGrow:1,minWidth:'29%',maxWidth:'48%',padding:12,borderRadius:12,backgroundColor:'white',borderWidth:1,borderColor:'#eadde5',gap:4},categoryCount:{fontSize:10,color:'#ac879b'},resultCount:{fontSize:12,color:'#7d6877'},filterPanel:{padding:15,borderRadius:18,backgroundColor:'#f5eaf0'},note:{fontSize:10,lineHeight:15,color:'#927987'},card:{backgroundColor:'white',borderRadius:18,overflow:'hidden',marginBottom:14},cardBody:{padding:12,gap:6},cardCategory:{fontSize:8,color:'#a0748b',fontWeight:'900',letterSpacing:1},productName:{fontSize:13,lineHeight:18,minHeight:36,fontWeight:'700',color:'#362936'},color:{fontSize:10,color:'#927b8a'},price:{fontSize:17,fontWeight:'900',color:'#67425a'},choose:{width:28,height:28,backgroundColor:'#a15078',borderRadius:14,alignItems:'center',justifyContent:'center'},heart:{position:'absolute',top:9,right:9,width:33,height:33,borderRadius:17,backgroundColor:'#fff7fb',alignItems:'center',justifyContent:'center'},empty:{padding:30,gap:16,alignItems:'center'}});
